### ISSUE TITLE
line 56: curl: command not found

### ISSUE THREAD

**Issue by jwhazel** [not-a-feature/wd_ssd_firmware_update#1]
Fun times. Was trying to do an update using a current Ubuntu live usb and it kept reporting that it couldn't find a "matching firmware URL" which I thought was strange because I had the xml pulled up in a browser tab and there was definitely a newer version. After manually flashing the drive I decided to scroll back through the terminal to try and figure out why your script wasn't working. 

Aha! _finally_ saw the `line 56: curl: command not found` and started kicking myself. Apparently it's possible for some distro's to not include cURL in 2024? 🤷 

Anyways, simple check along with the other 2 deps might save some others a few minutes of head scratching:
```
if ! required_curl="$(type -p "curl")" || [[ -z $required_curl ]]; then
  echo "The required package 'curl' is not installed."
  echo "Please install it using 'sudo apt install curl'."
  exit 1
fi
```

Edit: also... really appreciate you putting this script together. Huge help for the community.

**Comment by not-a-feature** [comment]
Wow, i never thought of  adding a check for curl.
Nice catch!
